"use client";

import {useEffect,useState,type FormEvent} from 'react';
import {LayoutDashboard,School as SchoolIcon,Users,ScrollText,LogOut,ArrowLeft,Wrench} from 'lucide-react';

type School={id:string;code:string;gre:number|null;name:string;library_name:string;city:string;state:string;status:string;contact_name:string;contact_phone:string;contact_email:string;license_start:string;license_end:string;last_access:string|null;users_count:number;books_count:number;loans_count:number};
type Member={id:string;username:string;display_name:string;owner:string;role:string;active:number;email:string;phone:string;last_login_at:string};
type Log={id:string;institution_id:string;user_id:string;action:string;details:string;created_at:string};
type AdminData={schools:School[];users:Member[];logs:Log[]};
type View='Visão Geral'|'Escolas'|'Usuários'|'Logs';
const nav:[View,typeof LayoutDashboard][]=[['Visão Geral',LayoutDashboard],['Escolas',SchoolIcon],['Usuários',Users],['Logs',ScrollText]];
const gres=Array.from({length:21},(_,i)=>i+1);
const greLabel=(value:number|null)=>value==null?'GRE não informada':`GRE ${String(value).padStart(2,'0')}`;
const fmt=(value:string|null)=>value?new Date(value).toLocaleString('pt-BR'):'—';
const count=(value:number)=>Number(value||0).toLocaleString('pt-BR');
const validGre=(value:number|null)=>value!==null&&Number.isInteger(value)&&value>=1&&value<=21;

export default function AdminConsole({username}:{username:string}){
 const [data,setData]=useState<AdminData|null>(null),[view,setView]=useState<View>('Visão Geral'),[schoolId,setSchoolId]=useState(''),[creating,setCreating]=useState(false),[editing,setEditing]=useState(false),[newUser,setNewUser]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[greFilter,setGreFilter]=useState<number|null>(null);
 const selected=data?.schools.find(s=>s.id===schoolId);
 const visibleSchools=data?.schools.filter(s=>s.gre===greFilter)||[];
 const totals=data?.schools.reduce((acc,s)=>({books:acc.books+Number(s.books_count),loans:acc.loans+Number(s.loans_count)}),{books:0,loans:0});
 async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});if(r.status===401){location.assign('/');return}const result=await r.json() as AdminData&{error?:string};if(!r.ok)throw Error(result.error||'Falha ao carregar escolas.');setData(result);setGreFilter(current=>current===null&&!result.schools.some(s=>s.gre===null)?result.schools.find(s=>validGre(s.gre))?.gre??null:current)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[]);
 async function post(payload:Record<string,unknown>):Promise<boolean>{setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string;id?:string};if(!r.ok)throw Error(d.error||'Não foi possível salvar.');if(payload.action==='enter-support'){location.assign('/sistema');return true}await load();setMessage(payload.action==='create-school'?'Escola cadastrada. Agora cadastre o primeiro usuário.':'Alterações salvas.');if(payload.action==='create-school'){setCreating(false);setSchoolId(d.id||'');setView('Escolas');setNewUser(true);setGreFilter(Number(payload.gre))}if(payload.action==='update-school'){setEditing(false);setGreFilter(Number(payload.gre))}if(payload.action==='create-user')setNewUser(false);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 function submit(e:FormEvent<HTMLFormElement>,action:string,extra:Record<string,unknown>={}){e.preventDefault();void post({...Object.fromEntries(new FormData(e.currentTarget)),...extra,action})}
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.assign('/')}
 const setPage=(page:View)=>{setView(page);setSchoolId('');setCreating(false);setEditing(false);setNewUser(false);setError('');setMessage('')};
 return <div className="admin-shell">
  <aside className="admin-sidebar"><div className="admin-identity"><img src="/admin-logo.png" alt="Logo Painel Admin"/><div><strong>Painel Admin</strong><small>SGB · Gestão institucional</small></div></div><div className="admin-nav-label">NAVEGAÇÃO</div><nav className="admin-nav" aria-label="Painel do Desenvolvedor">{nav.map(([name,Icon])=><button key={name} type="button" className={view===name?'active':''} onClick={()=>setPage(name)}><Icon size={18}/>{name}</button>)}</nav><div className="admin-sidebar-bottom"><span>Administrador</span><strong>{username}</strong></div></aside>
  <div className="admin-stage"><header className="admin-top"><span>Administração · SGB</span><div className="admin-top-profile"><span className="admin-initials">{username.slice(0,2).toUpperCase()}</span><strong>{username}</strong><button onClick={logout} type="button"><LogOut size={16}/> Sair</button></div></header><main className="admin-main"><div className="admin-heading"><div><small>PAINEL DE ADMINISTRAÇÃO</small><h1>{selected&&view==='Escolas'?selected.name:creating?'Cadastrar escola':view}</h1><p>{view==='Escolas'?'Gerencie as instituições por Gerência Regional.':view==='Usuários'?'Encontre os usuários pela GRE e pela escola.':view==='Logs'?'Ações registradas no sistema.':'Acompanhe o essencial da rede de bibliotecas.'}</p></div>{view==='Escolas'&&!creating&&<button className="admin-primary" onClick={()=>{setSchoolId('');setCreating(true);setEditing(false)}}>+ Cadastrar escola</button>}</div>
  {error&&<p role="alert" className="admin-error">{error}</p>}{message&&<p role="status" className="admin-success">{message}</p>}{!data&&<p className="admin-loading">Carregando dados…</p>}
  {data&&view==='Visão Geral'&&<><div className="admin-metrics"><div><span>Escolas</span><strong>{count(data.schools.length)}</strong></div><div><span>Livros cadastrados</span><strong>{count(totals?.books||0)}</strong></div><div><span>Empréstimos</span><strong>{count(totals?.loans||0)}</strong></div></div><section className="admin-box"><div className="admin-box-title"><h2>Escolas da rede</h2><button className="admin-link" onClick={()=>setPage('Escolas')}>Ver todas →</button></div><div className="admin-list">{data.schools.slice(0,5).map(s=><button key={s.id} className="admin-list-row" onClick={()=>{setView('Escolas');setSchoolId(s.id);setGreFilter(s.gre)}}><span><strong>{s.name}</strong><small>{greLabel(s.gre)} · {s.city||'Cidade não informada'}</small></span><span className={'admin-status '+s.status}>{s.status}</span></button>)}</div>{!data.schools.length&&<p>Nenhuma escola cadastrada.</p>}</section></>}
  {data&&view==='Escolas'&&(creating?<section className="admin-box"><SchoolForm busy={busy} onSubmit={e=>submit(e,'create-school')}/><button className="admin-link" onClick={()=>setCreating(false)}>Cancelar</button></section>:selected?<><button className="admin-back" onClick={()=>{setSchoolId('');setEditing(false);setNewUser(false)}}><ArrowLeft size={16}/> Voltar às escolas</button><section className="admin-box"><div className="admin-detail-heading"><div><span className="admin-gre-badge">{greLabel(selected.gre)}</span><h2>{selected.name}</h2><p>{selected.library_name||'Biblioteca não informada'} · {selected.city||'Cidade não informada'} / {selected.state||'—'} · {selected.code}</p></div><span className={'admin-status '+selected.status}>{selected.status}</span></div><div className="admin-detail-stats"><span><strong>{count(selected.books_count)}</strong> livros</span><span><strong>{count(selected.loans_count)}</strong> empréstimos</span><span><strong>{count(selected.users_count)}</strong> usuários</span></div><div className="admin-detail-info"><span>Responsável: <strong>{selected.contact_name||'Não informado'}</strong></span><span>Licença: <strong>{selected.license_start||'—'} até {selected.license_end||'—'}</strong></span></div><div className="admin-actions"><button className="admin-primary" disabled={busy} onClick={()=>void post({action:'enter-support',institutionId:selected.id})}><Wrench size={15}/> Acessar em modo suporte</button><button className="admin-secondary" onClick={()=>setEditing(v=>!v)}>Editar escola</button><button className="admin-secondary" onClick={()=>setNewUser(v=>!v)}>Novo usuário</button></div></section>{editing&&<section className="admin-box"><h2>Editar escola</h2><SchoolForm school={selected} busy={busy} onSubmit={e=>submit(e,'update-school',{id:selected.id})}/></section>}{newUser&&<section className="admin-box"><h2>Novo usuário · {selected.name}</h2><UserForm busy={busy} onSubmit={e=>submit(e,'create-user',{institutionId:selected.id})}/></section>}<section className="admin-box"><h2>Usuários desta escola</h2><UserTable users={data.users.filter(u=>u.owner===selected.id&&u.role!=='desenvolvedor')} busy={busy} onPost={post}/></section></>:<><GreFilter schools={data.schools} value={greFilter} onChange={setGreFilter}/><section className="admin-box"><div className="admin-box-title"><h2>{greLabel(greFilter)}</h2><span>{visibleSchools.length} {visibleSchools.length===1?'escola':'escolas'}</span></div><div className="admin-list">{visibleSchools.map(s=><button key={s.id} className="admin-list-row" onClick={()=>setSchoolId(s.id)}><span><strong>{s.name}</strong><small>{s.code} · {s.city||'Cidade não informada'} · {count(s.books_count)} livros</small></span><span className={'admin-status '+s.status}>{s.status}</span><span className="admin-open">Gerenciar →</span></button>)}</div>{!visibleSchools.length&&<p className="admin-empty">Nenhuma escola nesta GRE.</p>}</section></>)}
  {data&&view==='Usuários'&&<><GreFilter schools={data.schools} value={greFilter} onChange={setGreFilter}/>{visibleSchools.length?visibleSchools.map(s=><section className="admin-box" key={s.id}><div className="admin-box-title"><h2>{s.name}</h2><span>{s.code} · {greLabel(s.gre)}</span></div><UserTable users={data.users.filter(u=>u.owner===s.id&&u.role!=='desenvolvedor')} busy={busy} onPost={post}/></section>):<section className="admin-box"><p>Nenhuma escola nesta GRE.</p></section>}</>}
  {data&&view==='Logs'&&<section className="admin-box"><div className="admin-box-title"><h2>Atividade recente</h2><span>{data.logs.length} registros exibidos</span></div><div className="admin-scroll"><table><thead><tr><th>Quando</th><th>Escola</th><th>Usuário</th><th>Ação</th></tr></thead><tbody>{data.logs.map(l=><tr key={l.id}><td>{fmt(l.created_at)}</td><td>{data.schools.find(s=>s.id===l.institution_id)?.name||'—'}</td><td>{data.users.find(u=>u.id===l.user_id)?.username||'—'}</td><td>{l.action.replaceAll('_',' ')}</td></tr>)}</tbody></table></div>{!data.logs.length&&<p className="admin-empty">Ainda não há ações registradas.</p>}</section>}
  </main></div>
 </div>;
}

function GreFilter({schools,value,onChange}:{schools:School[];value:number|null;onChange:(value:number|null)=>void}){const unassigned=schools.filter(s=>s.gre==null).length;return <div className="admin-gre-filter"><label htmlFor="admin-gre">Gerência Regional</label><select id="admin-gre" value={value??'none'} onChange={e=>onChange(e.target.value==='none'?null:Number(e.target.value))}>{unassigned>0&&<option value="none">GRE não informada · {unassigned}</option>}{gres.map(g=><option value={g} key={g}>GRE {String(g).padStart(2,'0')} · {schools.filter(s=>s.gre===g).length} escolas</option>)}</select></div>}

function SchoolForm({school,onSubmit,busy}:{school?:School;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <form className="admin-form" onSubmit={onSubmit}><fieldset><legend>Dados da instituição</legend><div className="admin-fields"><label>Nome da escola *<input name="name" required maxLength={150} defaultValue={school?.name||''}/></label><label>Nome da biblioteca *<input name="library_name" required maxLength={150} defaultValue={school?.library_name||''}/></label><label>GRE *<select name="gre" required defaultValue={school?.gre??''}><option value="" disabled>Selecione a GRE</option>{gres.map(g=><option value={g} key={g}>GRE {String(g).padStart(2,'0')}</option>)}</select></label><label>Cidade *<input name="city" required maxLength={150} defaultValue={school?.city||''}/></label><label>Estado *<input name="state" required maxLength={50} defaultValue={school?.state||''}/></label></div></fieldset><fieldset><legend>Responsável</legend><div className="admin-fields"><label>Nome do responsável *<input name="contact_name" required maxLength={150} defaultValue={school?.contact_name||''}/></label><label>Telefone<input name="contact_phone" type="tel" maxLength={50} defaultValue={school?.contact_phone||''}/></label><label>E-mail<input name="contact_email" type="email" maxLength={200} defaultValue={school?.contact_email||''}/></label></div></fieldset><fieldset><legend>Acesso e licença</legend><div className="admin-fields"><label>Status<select name="status" defaultValue={school?.status||'ativa'}><option value="ativa">Ativa</option><option value="inativa">Inativa</option><option value="suspensa">Suspensa</option></select></label><label>Início da licença *<input name="license_start" type="date" required defaultValue={school?.license_start||''}/></label><label>Vencimento da licença *<input name="license_end" type="date" required defaultValue={school?.license_end||''}/></label></div></fieldset><div className="admin-form-actions"><button className="admin-primary" disabled={busy} type="submit">{busy?'Salvando…':school?'Salvar alterações':'Cadastrar escola'}</button></div></form>}
function UserForm({onSubmit,busy}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <form className="admin-form" onSubmit={onSubmit}><div className="admin-fields"><label>Nome<input name="display_name" required maxLength={150}/></label><label>Login<input name="username" required minLength={3} maxLength={50}/></label><label>Senha inicial<input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></label><label>Perfil<select name="role"><option value="bibliotecario">Bibliotecária</option><option value="direcao">Direção (consulta)</option></select></label><label>E-mail<input name="email" type="email"/></label><label>Telefone<input name="phone"/></label></div><button className="admin-primary" disabled={busy}>Criar usuário</button></form>}
function UserTable({users,busy,onPost}:{users:Member[];busy:boolean;onPost:(data:Record<string,unknown>)=>Promise<boolean>}){const [editing,setEditing]=useState(''),[reset,setReset]=useState('');return <div className="admin-scroll"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.display_name||u.username}</strong><small>{u.username}</small></td><td>{u.role==='direcao'?'Direção':'Bibliotecária'}</td><td><span className={'admin-status '+(u.active?'ativa':'inativa')}>{u.active?'Ativo':'Inativo'}</span></td><td><button className="admin-link" onClick={()=>{setEditing(u.id);setReset('')}}>Editar</button><button className="admin-link" onClick={()=>{setReset(u.id);setEditing('')}}>Redefinir senha</button></td></tr>)}</tbody></table>{!users.length&&<p className="admin-empty">Nenhum usuário cadastrado nesta escola.</p>}{editing&&<form className="admin-form admin-inline-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await onPost({action:'update-user',id:editing,role:f.get('role'),active:f.get('active')==='on',display_name:f.get('display_name'),email:f.get('email'),phone:f.get('phone')}))setEditing('')}}><h3>Editar {users.find(u=>u.id===editing)?.username}</h3><div className="admin-fields"><label>Nome<input name="display_name" required defaultValue={users.find(u=>u.id===editing)?.display_name||users.find(u=>u.id===editing)?.username}/></label><label>Perfil<select name="role" defaultValue={users.find(u=>u.id===editing)?.role}><option value="bibliotecario">Bibliotecária</option><option value="direcao">Direção</option></select></label><label className="admin-check">Ativo<input type="checkbox" name="active" defaultChecked={!!users.find(u=>u.id===editing)?.active}/></label><label>E-mail<input name="email" type="email" defaultValue={users.find(u=>u.id===editing)?.email}/></label><label>Telefone<input name="phone" defaultValue={users.find(u=>u.id===editing)?.phone}/></label></div><button className="admin-primary" disabled={busy}>Salvar usuário</button></form>}{reset&&<form className="admin-form admin-inline-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await onPost({action:'reset-password',id:reset,password:f.get('password')}))setReset('')}}><h3>Redefinir senha de {users.find(u=>u.id===reset)?.username}</h3><label>Nova senha<input name="password" type="password" minLength={10} maxLength={128} required autoComplete="new-password"/></label><button className="admin-primary" disabled={busy}>Salvar nova senha</button></form>}</div>}
