"use client";

import {useEffect,useState,type FormEvent} from 'react';
import {SGB_VERSION} from '../version';

type School={id:string;code:string;name:string;library_name:string;city:string;state:string;status:string;created_at:string;last_access:string|null;users_count:number;books_count:number;copies_count:number;loans_count:number;active_loans:number;late_loans:number;students_count:number;shelves_count:number;[key:string]:string|number|null};
type Member={id:string;username:string;display_name:string;owner:string;role:string;active:number;email:string;phone:string;last_login_at:string};
type Log={id:string;institution_id:string;user_id:string;action:string;details:string;created_at:string};
type AdminData={schools:School[];users:Member[];logs:Log[];checkedAt:string};
const sections=['Visão Geral','Escolas','Usuários','Sistema','Banco de Dados','Logs','Backups','Atualizações','Configurações'];
const schoolFields:[string,string][]=[['name','Nome da escola'],['library_name','Nome da biblioteca'],['code','Código da instituição (automático se vazio)'],['cnpj','CNPJ (opcional)'],['city','Cidade'],['state','Estado'],['cep','CEP'],['address','Endereço'],['address_number','Número'],['district','Bairro'],['phone','Telefone'],['email','E-mail'],['contact_name','Nome do responsável'],['contact_role','Cargo do responsável'],['contact_phone','Telefone do responsável'],['contact_email','E-mail do responsável'],['logo_url','Endereço da logo (URL)'],['activated_at','Data de ativação'],['notes','Observações']];
const licenseFields:[string,string][]=[['license_plan','Plano'],['license_status','Status da licença'],['license_start','Início da licença'],['license_end','Vencimento da licença'],['license_notes','Observação da licença']];
const fmt=(v:string|null|undefined)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const count=(n:number)=>Number(n||0).toLocaleString('pt-BR');

export default function AdminConsole({username}:{username:string}){
 const [data,setData]=useState<AdminData|null>(null),[view,setView]=useState('Visão Geral'),[schoolId,setSchoolId]=useState(''),[creating,setCreating]=useState(false),[editing,setEditing]=useState(false),[newUser,setNewUser]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const selected=data?.schools.find(s=>s.id===schoolId);
 async function load(){try{const r=await fetch('/api/admin',{cache:'no-store'});if(r.status===401){location.assign('/');return}const result=await r.json() as AdminData&{error?:string};if(!r.ok)throw Error(result.error);setData(result)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function post(payload:Record<string,unknown>){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json() as {error?:string;id?:string};if(!r.ok)throw Error(d.error);if(payload.action==='enter-support'){location.assign('/sistema');return}await load();setMessage(payload.action==='create-school'?'Escola cadastrada com sucesso. Crie o primeiro usuário.':'Alterações salvas.');if(payload.action==='create-school'){setCreating(false);setSchoolId(d.id||'');setView('Escolas');setNewUser(true)}else if(payload.action==='update-school')setEditing(false);else if(payload.action==='create-user')setNewUser(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>,action:string,extras:Record<string,unknown>={}){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget).entries());await post({...values,...extras,action})}
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.assign('/')}
 const totals=data?.schools.reduce((a,s)=>({books:a.books+Number(s.books_count),copies:a.copies+Number(s.copies_count),loans:a.loans+Number(s.loans_count),active:a.active+Number(s.active_loans),students:a.students+Number(s.students_count),users:a.users+Number(s.users_count)}),{books:0,copies:0,loans:0,active:0,students:0,users:0});
 return <div className="admin-shell"><header className="admin-top"><div><strong>SGB</strong><small>Administração da plataforma</small></div><span>{username} · Desenvolvedor</span><button type="button" onClick={logout}>Sair</button></header><div className="admin-layout"><nav className="admin-nav" aria-label="Painel do Desenvolvedor">{sections.map(s=><button key={s} type="button" className={view===s?'active':''} onClick={()=>{setView(s);setCreating(false);setEditing(false);setNewUser(false)}}>{s}</button>)}</nav><main className="admin-main"><div className="admin-heading"><div><small>PAINEL SGB</small><h1>{selected&&view==='Escolas'?selected.name:view}</h1></div>{view==='Escolas'&&<button className="admin-primary" onClick={()=>{setSchoolId('');setCreating(true);setEditing(false)}}>+ Cadastrar Escola</button>}</div>{error&&<p role="alert" className="admin-error">{error}</p>}{message&&<p role="status" className="admin-success">{message}</p>}{!data&&<p>Carregando dados das escolas…</p>}
 {data&&view==='Visão Geral'&&<><div className="admin-metrics">{[['Escolas',data.schools.length],['Ativas',data.schools.filter(s=>s.status==='ativa').length],['Inativas / suspensas',data.schools.filter(s=>s.status!=='ativa').length],['Usuários',totals!.users],['Livros',totals!.books],['Exemplares',totals!.copies],['Alunos registrados em empréstimos',totals!.students],['Empréstimos',totals!.loans],['Empréstimos ativos',totals!.active]].map(([name,value])=><div key={name}><small>{name}</small><strong>{count(Number(value))}</strong></div>)}</div><div className="admin-box"><h2>Estado do sistema</h2><p>API e banco de dados: conectados · Versão {SGB_VERSION}</p><p>Atividade recente: {data.logs.length?data.logs.slice(0,5).map(l=><span className="admin-line" key={l.id}>{fmt(l.created_at)} · {l.action} · {data.schools.find(s=>s.id===l.institution_id)?.name||'Escola não encontrada'}</span>):'Nenhuma ação registrada desde a ativação do histórico.'}</p></div></>}
 {data&&view==='Escolas'&&<>{creating?<div className="admin-box"><h2>Cadastrar escola</h2><SchoolForm onSubmit={e=>submit(e,'create-school')} busy={busy}/><button className="admin-secondary" onClick={()=>setCreating(false)}>Cancelar</button></div>:selected?<><button className="admin-secondary" onClick={()=>{setSchoolId('');setEditing(false)}}>← Todas as escolas</button><div className="admin-metrics">{[['Livros',selected.books_count],['Exemplares',selected.copies_count],['Alunos',selected.students_count],['Empréstimos ativos',selected.active_loans],['Atrasados',selected.late_loans],['Usuários',selected.users_count],['Prateleiras em uso',selected.shelves_count]].map(([name,value])=><div key={name}><small>{name}</small><strong>{count(Number(value))}</strong></div>)}</div><div className="admin-box"><h2>Informações da escola</h2><p>Código: {selected.code} · {selected.city||'Cidade não informada'} / {selected.state||'—'} · {selected.status}</p><p>Contato: {selected.contact_name||'—'} · {selected.phone||'—'} · Último acesso: {fmt(selected.last_access)}</p><div className="admin-actions"><button className="admin-primary" disabled={busy} onClick={()=>post({action:'enter-support',institutionId:selected.id})}>Entrar no SGB</button><button className="admin-secondary" onClick={()=>setEditing(v=>!v)}>Editar escola e licença</button><button className="admin-secondary" onClick={()=>setNewUser(v=>!v)}>Criar primeiro usuário / Novo usuário</button></div>{editing&&<SchoolForm school={selected} onSubmit={e=>submit(e,'update-school',{id:selected.id})} busy={busy}/>}</div>{newUser&&<div className="admin-box"><h2>Criar usuário para {selected.name}</h2><UserForm busy={busy} onSubmit={e=>submit(e,'create-user',{institutionId:selected.id})}/></div>}<div className="admin-box"><h2>Usuários da escola</h2><UserTable users={data.users.filter(u=>u.owner===selected.id&&u.role!=='desenvolvedor')} busy={busy} onPost={post}/></div></>:<div className="admin-box admin-scroll"><table><thead><tr>{['Escola','Cidade','Estado','Responsável','Usuários','Livros','Empréstimos','Status','Último acesso','Ações'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.schools.map(s=><tr key={s.id}><td>{s.name}<small>{s.code}</small></td><td>{s.city||'—'}</td><td>{s.state||'—'}</td><td>{s.contact_name||'—'}</td><td>{count(s.users_count)}</td><td>{count(s.books_count)}</td><td>{count(s.loans_count)}</td><td>{s.status}</td><td>{fmt(s.last_access)}</td><td><button className="admin-secondary" onClick={()=>setSchoolId(s.id)}>Gerenciar</button></td></tr>)}</tbody></table></div>}</>}
 {data&&view==='Usuários'&&<div className="admin-box"><h2>Usuários por instituição</h2><UserTable users={data.users.filter(u=>u.role!=='desenvolvedor')} busy={busy} onPost={post} schools={data.schools}/></div>}
 {data&&view==='Sistema'&&<div className="admin-box"><h2>Serviço</h2><p>Versão: {SGB_VERSION} · Escolas cadastradas: {data.schools.length}</p><p>O acesso de cada escola é identificado pelo login do usuário. Escolas suspensas e inativas não conseguem entrar.</p></div>}
 {data&&view==='Banco de Dados'&&<div className="admin-box"><h2>Dados armazenados</h2><p>Livros: {count(totals!.books)} · Exemplares: {count(totals!.copies)} · Empréstimos: {count(totals!.loans)}</p><p>As contagens vêm dos registros do banco. A exclusão de bancos e escolas não é oferecida neste painel.</p></div>}
 {data&&view==='Logs'&&<div className="admin-box admin-scroll"><h2>Atividade registrada</h2><table><thead><tr><th>Data</th><th>Escola</th><th>Usuário</th><th>Ação</th><th>Detalhes</th></tr></thead><tbody>{data.logs.map(l=><tr key={l.id}><td>{fmt(l.created_at)}</td><td>{data.schools.find(s=>s.id===l.institution_id)?.name||'—'}</td><td>{data.users.find(u=>u.id===l.user_id)?.username||'—'}</td><td>{l.action}</td><td>{l.details||'—'}</td></tr>)}</tbody></table>{!data.logs.length&&<p>O histórico passa a ser registrado depois da migração.</p>}</div>}
 {data&&view==='Backups'&&<div className="admin-box"><h2>Cópias de segurança</h2><p>O backup completo do D1 deve ser gerado no painel da Cloudflare antes de qualquer migração. Este painel não altera nem apaga backups.</p><p>Livros: {count(totals!.books)} · Empréstimos: {count(totals!.loans)} · Usuários: {count(totals!.users)}</p></div>}
 {data&&view==='Atualizações'&&<div className="admin-box"><h2>Versão instalada</h2><p>SGB {SGB_VERSION}</p><p>As escolas usam a mesma implantação da plataforma.</p></div>}
 {data&&view==='Configurações'&&<div className="admin-box"><h2>Configurações institucionais</h2><p>Abra Escolas → Gerenciar → Editar escola e licença para ajustar os dados de cada instituição.</p></div>}
 </main></div></div>;
}

function SchoolForm({school,onSubmit,busy}:{school?:School;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <form className="admin-form" onSubmit={onSubmit}><div className="admin-fields">{schoolFields.map(([key,label])=><label key={key}>{label}<input name={key} type={key==='activated_at'?'date':key.includes('email')?'email':key==='logo_url'?'url':'text'} defaultValue={String(school?.[key]??'')} required={key==='name'} maxLength={key==='notes'?1000:200} readOnly={key==='code'&&!!school}/></label>)}<label>Status<select name="status" defaultValue={school?.status||'ativa'}><option value="ativa">Ativa</option><option value="suspensa">Suspensa</option><option value="inativa">Inativa</option></select></label></div><h3>Licença</h3><div className="admin-fields">{licenseFields.map(([key,label])=><label key={key}>{label}<input name={key} type={key==='license_start'||key==='license_end'?'date':'text'} defaultValue={String(school?.[key]??(key==='license_plan'?'Educacional':key==='license_status'?'Ativa':''))}/></label>)}</div><button className="admin-primary" disabled={busy} type="submit">{busy?'Salvando…':school?'Salvar escola':'Cadastrar escola'}</button></form>}
function UserForm({onSubmit,busy}:{onSubmit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <form className="admin-form" onSubmit={onSubmit}><div className="admin-fields"><label>Nome<input name="display_name" required maxLength={150}/></label><label>Login<input name="username" required minLength={3} maxLength={50}/></label><label>Senha inicial<input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></label><label>Perfil<select name="role"><option value="bibliotecario">Bibliotecária</option><option value="direcao">Direção (consulta)</option></select></label><label>E-mail<input name="email" type="email"/></label><label>Telefone<input name="phone"/></label></div><button className="admin-primary" type="submit" disabled={busy}>Criar usuário</button></form>}
function UserTable({users,busy,onPost,schools}:{users:Member[];busy:boolean;onPost:(data:Record<string,unknown>)=>Promise<void>;schools?:School[]}){const [editing,setEditing]=useState(''),[reset,setReset]=useState('');return <div className="admin-scroll"><table><thead><tr><th>Login</th><th>Escola</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.display_name||u.username}<small>{u.username}</small></td><td>{schools?.find(s=>s.id===u.owner)?.name||'Escola atual'}</td><td>{u.role==='direcao'?'Direção':'Bibliotecária'}</td><td>{u.active?'Ativo':'Desativado'}</td><td>{fmt(u.last_login_at)}</td><td><button className="admin-secondary" onClick={()=>{setEditing(u.id);setReset('')}}>Editar</button> <button className="admin-secondary" onClick={()=>{setReset(u.id);setEditing('')}}>Redefinir senha</button></td></tr>)}</tbody></table>{editing&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onPost({action:'update-user',id:editing,role:f.get('role'),active:f.get('active')==='on',display_name:f.get('display_name'),email:f.get('email'),phone:f.get('phone')}).then(()=>setEditing(''))}}><h3>Editar {users.find(u=>u.id===editing)?.username}</h3><div className="admin-fields"><label>Nome<input name="display_name" required defaultValue={users.find(u=>u.id===editing)?.display_name||users.find(u=>u.id===editing)?.username}/></label><label>Perfil<select name="role" defaultValue={users.find(u=>u.id===editing)?.role}><option value="bibliotecario">Bibliotecária</option><option value="direcao">Direção (consulta)</option></select></label><label>Ativo<input type="checkbox" name="active" defaultChecked={!!users.find(u=>u.id===editing)?.active}/></label><label>E-mail<input name="email" type="email" defaultValue={users.find(u=>u.id===editing)?.email}/></label><label>Telefone<input name="phone" defaultValue={users.find(u=>u.id===editing)?.phone}/></label></div><button className="admin-primary" disabled={busy}>Salvar</button></form>}{reset&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onPost({action:'reset-password',id:reset,password:f.get('password')}).then(()=>setReset(''))}}><h3>Redefinir senha de {users.find(u=>u.id===reset)?.username}</h3><label>Nova senha<input name="password" type="password" minLength={10} maxLength={128} required autoComplete="new-password"/></label><button className="admin-primary" disabled={busy}>Salvar nova senha</button></form>}</div>}
