import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
import JsBarcode from 'jsbarcode';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const compile=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64');
const rules=await import(compile(readFileSync('app/label-rules.ts','utf8')));
const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');
for(const path of readdirSync('drizzle').filter(p=>/^000[0-5].*\.sql$/.test(p)).sort())db.exec(readFileSync('drizzle/'+path,'utf8'));
db.prepare('INSERT INTO institutions(id,code,name) VALUES(?,?,?)').run('a','SGB-0001','Escola A');
db.prepare('INSERT INTO institutions(id,code,name) VALUES(?,?,?)').run('b','SGB-0002','Escola B');
for(let i=0;i<1614;i++)db.prepare('INSERT INTO books(id,owner,registration,data) VALUES(?,?,?,?)').run('book-'+i,'a',String(i),JSON.stringify({title:'Livro '+i,authors:'Autor',registration:String(i),copies:'1'}));
db.prepare('INSERT INTO books(id,owner,registration,data) VALUES(?,?,?,?)').run('other','b','1847','{"title":"Outro livro"}');
db.prepare('INSERT INTO users(id,username,owner,salt,hash,role) VALUES(?,?,?,?,?,?)').run('u','leila','a','salt','hash','bibliotecario');
db.prepare('INSERT INTO loans(id,owner,data) VALUES(?,?,?)').run('old-loan','a','{"student":"Marcos","code":"1"}');
db.prepare('INSERT INTO sessions(token_hash,user_id,expires) VALUES(?,?,?)').run('fixture','u','9999999999999');
const snapshots=new Map(['books','users','sessions','loans','institutions'].map(t=>[t,db.prepare('SELECT * FROM '+t+' ORDER BY rowid').all()]));
db.exec(readFileSync('drizzle/0006_book_labels.sql','utf8'));
for(const [table,rows] of snapshots)assert.deepEqual(db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),rows);
assert.equal(db.prepare('SELECT COUNT(*) AS n,COUNT(DISTINCT code) AS codes FROM book_labels').get().n,1615);
assert.equal(db.prepare('SELECT COUNT(DISTINCT code) AS n FROM book_labels').get().n,1615);
const identity=db.prepare('SELECT code FROM book_labels WHERE book_id=?').get('book-0').code;
assert.match(identity,/^SGB-0001-\d{6}$/);
db.prepare('UPDATE books SET registration=?,data=? WHERE id=?').run('9999','{"title":"Novo título"}','book-0');
assert.equal(db.prepare('SELECT code FROM book_labels WHERE book_id=?').get('book-0').code,identity);
assert.throws(()=>db.prepare('UPDATE book_labels SET institution_code=? WHERE book_id=?').run('0002','book-0'));
db.prepare('INSERT INTO books(id,owner,registration,data) VALUES(?,?,?,?)').run('clone','a','9000','{"title":"Clone"}');
assert.notEqual(db.prepare('SELECT code FROM book_labels WHERE book_id=?').get('clone').code,identity);
// Numeração repetida em dados legados não participa da identidade da etiqueta.
db.exec('DROP INDEX books_owner_registration');
db.prepare('INSERT INTO books(id,owner,registration,data) VALUES(?,?,?,?)').run('duplicate-register','a','9000','{"title":"Outro exemplar"}');
assert.equal(db.prepare('SELECT COUNT(DISTINCT l.code) AS n FROM book_labels l JOIN books b ON b.id=l.book_id WHERE b.owner=? AND b.registration=?').get('a','9000').n,2);
db.prepare('INSERT INTO books(id,owner,registration,data) VALUES(?,?,?,?)').run('multiple','a','7000','{"title":"Vários exemplares","copies":"3"}');
const copyCodes=db.prepare('SELECT code FROM book_labels WHERE book_id=? ORDER BY copy_number').all('multiple');assert.equal(copyCodes.length,3);
db.prepare('UPDATE books SET data=? WHERE id=?').run('{"copies":"4"}','multiple');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM book_labels WHERE book_id=?').get('multiple').n,4);
db.prepare('UPDATE books SET data=? WHERE id=?').run('{"copies":"1"}','multiple');
db.prepare('UPDATE books SET data=? WHERE id=?').run('{"copies":"3"}','multiple');assert.deepEqual(db.prepare('SELECT code FROM book_labels WHERE book_id=? AND copy_number<=3 ORDER BY copy_number').all('multiple'),copyCodes);
const adapter={prepare(sql){const query={args:[],bind(...args){this.args=args;return this},async all(){return {results:db.prepare(sql).all(...this.args)}},async run(){return db.prepare(sql).run(...this.args)}};return query},async batch(queries){db.exec('BEGIN');try{const result=await Promise.all(queries.map(q=>q.run()));db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};
globalThis.__labelsDb=adapter;globalThis.__labelsUser={id:'u',institutionId:'a',institutionName:'Escola A',userId:'a',role:'bibliotecario'};globalThis.__labelIds=rules.labelIds;
let source=readFileSync('app/api/labels/route.ts','utf8').replace(/^import .*;\n/gm,'');
source='const getUser=async()=>globalThis.__labelsUser; const database=()=>globalThis.__labelsDb; const labelIds=globalThis.__labelIds;\n'+source;
const api=await import(compile(source));
const request=(body,origin='https://sgb.test')=>new Request('https://sgb.test/api/labels',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const first=await (await api.GET(new Request('https://sgb.test/api/labels'))).json();assert.equal(first.books.length,1619);assert.ok(!first.books.some(b=>b.bookId==='other'));
const lookup=await (await api.GET(new Request('https://sgb.test/api/labels?code='+identity))).json();assert.equal(lookup.books.length,1);assert.equal(lookup.books[0].bookId,'book-0');
const ids=Array.from({length:30},(_,i)=>String(db.prepare('SELECT id FROM book_labels WHERE book_id=?').get('book-'+i).id)),jobId=crypto.randomUUID();
assert.equal((await api.POST(request({action:'confirm-print',ids,jobId}))).status,200);
assert.equal((await api.POST(request({action:'confirm-print',ids,jobId}))).status,200);
assert.equal(db.prepare('SELECT print_count FROM book_labels WHERE book_id=?').get('book-0').print_count,1);
assert.equal((await api.POST(request({action:'confirm-print',ids,jobId:crypto.randomUUID()}))).status,200);
assert.equal(db.prepare('SELECT print_count FROM book_labels WHERE book_id=?').get('book-0').print_count,2);
assert.ok(db.prepare('SELECT last_printed_at FROM book_labels WHERE book_id=?').get('book-0').last_printed_at);
assert.equal((await api.POST(request({action:'confirm-print',ids:[ids[0],String(db.prepare('SELECT id FROM book_labels WHERE book_id=?').get('other').id)],jobId:crypto.randomUUID()}))).status,409);
assert.equal((await api.POST(request({action:'confirm-print',ids,jobId},'https://evil.test'))).status,403);
globalThis.__labelsUser.role='direcao';assert.equal((await api.POST(request({action:'confirm-print',ids,jobId}))).status,403);
globalThis.__labelsUser={id:'dev',institutionId:'b',institutionName:'Escola B',userId:'b',role:'desenvolvedor',supportMode:true};
assert.equal((await (await api.GET(new Request('https://sgb.test/api/labels'))).json()).books.length,1);
assert.equal((await (await api.GET(new Request('https://sgb.test/api/labels?code='+identity))).json()).books.length,0);
globalThis.__labelsUser=null;assert.equal((await api.GET(new Request('https://sgb.test/api/labels'))).status,401);
const rows=[{id:'one',code:identity,registration:'9999',title:'O Pequeno Príncipe',authors:'Antoine',printCount:2},{id:'two',code:'SGB-0001-000002',registration:'22',title:'Dom Casmurro',authors:'Machado',printCount:0}];
for(const query of ['principe','ANTOINE','9999',identity])assert.equal(rules.filterLabels(rows,query,'all')[0].id,'one');
assert.equal(rules.filterLabels(rows,'','printed').length,1);assert.equal(rules.filterLabels(rows,'','unprinted')[0].id,'two');
assert.deepEqual(rules.labelIds(['one','one']),['one']);assert.throws(()=>rules.labelIds([]));assert.throws(()=>rules.labelIds(new Array(5001).fill('one')));
for(const size of ['50x30','50x25','40x30'])assert.ok(rules.validLabelSize(size));assert.ok(!rules.validLabelSize('100x200'));
globalThis.__JsBarcode=JsBarcode;
const barcodeSource=readFileSync('app/label-barcode.tsx','utf8').split('export default')[0].replace("import JsBarcode from 'jsbarcode';",'const JsBarcode=globalThis.__JsBarcode;');
const {encodeLabel}=await import(compile(barcodeSource));
const binaries=[identity,'SGB-0002-999999','SGB-0001-1000000'].map(code=>({code,bits:encodeLabel(code)}));
for(const sample of binaries){assert.match(sample.bits,/^[01]+$/);assert.equal(sample.bits,encodeLabel(sample.code));}
writeFileSync(join(tmpdir(),'sgb-label-code128.json'),JSON.stringify(binaries));
const menu=readFileSync('app/extra-menu.tsx','utf8');assert.ok(!/onMouseLeave|onMouseOut/.test(menu));assert.ok(menu.includes('setOpen(value=>!value)'));assert.ok(menu.includes('Etiquetas e códigos'));
console.log('PASS: 1614 livros preservados; códigos únicos e imutáveis; novos exemplares; registros repetidos; reimpressão idempotente; lote de 30; busca exata; escolas isoladas; modo suporte; filtros e tamanhos; Code 128.');
db.close();
