import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
const source=readFileSync('app/student-report-format.ts','utf8');
const {studentReportCsv}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64'));
const csv=studentReportCsv([{code:'ALU-000001',name:'Marcos',grade:'2º A',createdAt:'2026-10-01',loans:[{title:'Livro A',code:'10',status:'Devolvido',delivery:'2026-09-01'},{title:'Livro B',code:'11',status:'Emprestado',delivery:'2026-10-01'}]},{code:'ALU-000002',name:'=FORMULA',grade:'1º B',createdAt:'2026-10-01',loans:[]}]);
assert.ok(csv.startsWith('\uFEFF'));
assert.equal(csv.split('\r\n').length,4);
assert.ok(csv.includes('"Marcos";"2º A";"2026-10-01";"2";"1";"1";"2026-10-01"'));
assert.ok(csv.includes("\"'=FORMULA\""));
assert.ok(csv.includes('Livro A')&&csv.includes('Livro B'));
assert.ok(!csv.includes('"title"'));
assert.equal(studentReportCsv([]).split('\r\n').length,1);
const menu=readFileSync('app/extra-menu.tsx','utf8');
assert.ok(menu.includes('target="_blank"'));
assert.ok(!menu.includes('unavailable')&&!menu.includes('Configurações')&&!menu.includes('Alunos que mais pegaram'));
console.log('Relatório: todos os alunos, múltiplos livros, totais, cabeçalhos em português, CSV seguro e menu sem duplicações: OK');
// Executa as consultas reais do relatório contra SQLite, com o mesmo contrato D1.
const {DatabaseSync}=await import('node:sqlite');
const {readdirSync}=await import('node:fs');
const db=new DatabaseSync(':memory:');
for(const path of readdirSync('drizzle').filter(p=>/^000[0-5].*\.sql$/.test(p)).sort())db.exec(readFileSync('drizzle/'+path,'utf8'));
const d1={prepare(sql){return {bind(...args){return {query:()=>db.prepare(sql).all(...args)}}}},async batch(queries){return queries.map(q=>({results:q.query()}))}};
globalThis.__studentReportDb=d1;
db.prepare('INSERT INTO students(id,owner,name,grade,name_key,grade_key) VALUES(?,?,?,?,?,?)').run(1,'a','Marcos','2º A','marcos','2 a');
db.prepare('INSERT INTO students(id,owner,name,grade,name_key,grade_key) VALUES(?,?,?,?,?,?)').run(2,'a','Maria','1º B','maria','1 b');
db.prepare('INSERT INTO students(id,owner,name,grade,name_key,grade_key) VALUES(?,?,?,?,?,?)').run(3,'b','Outro aluno','2º A','outro','2 a');
for(const [id,owner,student,title] of [['l1','a',1,'Livro A'],['l2','a',1,'Livro B'],['l3','b',3,'Livro secreto'],['l4','b',1,'Vínculo indevido']])db.prepare('INSERT INTO loans(id,owner,student_id,data) VALUES(?,?,?,?)').run(id,owner,student,JSON.stringify({title,delivery:'2026-10-01'}));
let dataSource=readFileSync('app/student-report-data.ts','utf8').replace(/^import .*;\n/gm,'').replace('export {studentReportCsv};','');
dataSource='const database=()=>globalThis.__studentReportDb; const associateLegacyLoans=async()=>{}; const studentCode=id=>`ALU-${String(id).padStart(6,"0")}`;\n'+dataSource;
const {loadStudentReport}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpileModule(dataSource,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText).toString('base64'));
const report=await loadStudentReport('a');
assert.equal(report.length,2);
assert.equal(report[0].code,'ALU-000001');
assert.equal(report[0].loans.length,2);
assert.equal(report[1].loans.length,0);
assert.ok(!JSON.stringify(report).includes('secreto')&&!JSON.stringify(report).includes('indevido'));
const other=await loadStudentReport('b');assert.equal(other.length,1);assert.equal(other[0].loans.length,1);
db.close();delete globalThis.__studentReportDb;
console.log('SQL real: todos os alunos, escola isolada e vínculos de empréstimos limitados à escola: OK');
