import {env} from 'cloudflare:workers';
import {database} from '@/db/raw';
import {COOKIE,digest,passwordHash,equal,hex} from '../../auth';
import {cookies} from 'next/headers';
const options={httpOnly:true,secure:true,sameSite:'strict' as const,path:'/'};
export async function GET(){try{const row=await database().prepare('SELECT id FROM users LIMIT 1').first();const dev=await database().prepare("SELECT id FROM users WHERE role='desenvolvedor' LIMIT 1").first();return Response.json({setup:!row,developerSetup:!!row&&!dev},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'Não foi possível acessar o sistema.'},{status:503})}}
export async function POST(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Origem inválida'},{status:403});try{const body=await req.json() as Record<string,string>;const db=database();const jar=await cookies();if(body.action==='logout'){const token=jar.get(COOKIE)?.value;if(token)await db.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();jar.set(COOKIE,'',{...options,maxAge:0});return Response.json({ok:true})}
const username=(body.username||'').trim().toLowerCase(),password=body.password||'';if(!/^[a-z0-9._-]{3,50}$/.test(username)||password.length<10||password.length>128)return Response.json({error:'Use um usuário de 3 a 50 caracteres e senha de 10 a 128 caracteres.'},{status:400});
const key=await digest((req.headers.get('cf-connecting-ip')||'unknown'));const now=Date.now();await db.prepare('INSERT INTO attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN CAST(until AS INTEGER) < ? THEN 1 ELSE CAST(count AS INTEGER)+1 END, until=CASE WHEN CAST(until AS INTEGER) < ? THEN ? ELSE until END').bind(key,now+900000,now,now,now+900000).run();const tries=await db.prepare('SELECT count FROM attempts WHERE key=?').bind(key).first<{count:string}>();if(Number(tries?.count)>10)return Response.json({error:'Muitas tentativas. Aguarde 15 minutos.'},{status:429});
if(body.action==='developer-setup'){const secret=(env as unknown as Record<string,string>).SGB_DEVELOPER_CODE;if(!secret||!equal(await digest(body.code||''),await digest(secret)))return Response.json({error:'Código de desenvolvedor inválido.'},{status:403});const librarian=await db.prepare("SELECT owner FROM users WHERE role='bibliotecario' LIMIT 1").first<{owner:string}>();if(!librarian)return Response.json({error:'Cadastre primeiro a bibliotecária.'},{status:409});const existing=await db.prepare("SELECT id FROM users WHERE role='desenvolvedor' OR username=?").bind(username).first();if(existing)return Response.json({error:'O perfil de desenvolvedor já existe ou esse usuário está em uso.'},{status:409});const salt=hex(crypto.getRandomValues(new Uint8Array(24)).buffer);const created=await db.prepare("INSERT INTO users(id,username,owner,salt,hash,role) SELECT 'developer',?,?,?,?,'desenvolvedor' WHERE NOT EXISTS(SELECT 1 FROM users WHERE role='desenvolvedor')").bind(username,librarian.owner,salt,await passwordHash(password,salt)).run();if(!created.meta.changes)return Response.json({error:'O perfil já foi criado. Entre com sua senha.'},{status:409});}
if(body.action==='setup'){const secret=(env as unknown as Record<string,string>).SGB_SETUP_CODE;if(!secret||!equal(await digest(body.code||''),await digest(secret)))return Response.json({error:'Código de ativação inválido.'},{status:403});const ownerRows=await db.prepare('SELECT DISTINCT owner FROM books UNION SELECT DISTINCT owner FROM loans').all<{owner:string}>();if(ownerRows.results.length>1)throw Error('Existing owner conflict');const owner=ownerRows.results[0]?.owner||crypto.randomUUID();const salt=hex(crypto.getRandomValues(new Uint8Array(24)).buffer);await db.prepare("INSERT INTO users(id,username,owner,salt,hash) SELECT 'administrator',?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM users)").bind(username,owner,salt,await passwordHash(password,salt)).run();}
const user=await db.prepare('SELECT id,salt,hash FROM users WHERE username=?').bind(username).first<{id:string;salt:string;hash:string}>();const computed=await passwordHash(password,user?.salt||'invalid-user-salt');if(!user||!equal(computed,user.hash))return Response.json({error:'Usuário ou senha incorretos.'},{status:401});const token=hex(crypto.getRandomValues(new Uint8Array(32)).buffer);await db.batch([db.prepare('DELETE FROM sessions WHERE CAST(expires AS INTEGER)<?').bind(now),db.prepare('INSERT INTO sessions(token_hash,user_id,expires) VALUES(?,?,?)').bind(await digest(token),user.id,now+8*3600000),db.prepare('DELETE FROM attempts WHERE key=?').bind(key)]);jar.set(COOKIE,token,{...options,maxAge:8*3600});return Response.json({ok:true});}catch(e){console.error('Authentication failed',e);return Response.json({error:'Não foi possível concluir o acesso. Tente novamente.'},{status:503})}}
