'use client';
import {useEffect,useState} from 'react';
import {BarChart,Bar,CartesianGrid,LineChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import './dashboard.css';

type Summary={metrics:{loans:number;students:number;books:number;active:number};timeline:{key:string;label:string;total:number}[];topStudents:{id:string;name:string;grade:string;total:number}[];topBooks:{title:string;author:string;total:number}[];grades:{grade:string;total:number}[];availableGrades:string[]};
type Range='hoje'|'semana'|'mes'|'ano'|'personalizado';
const dateString=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function rangeDates(range:Range,customStart:string,customEnd:string){const today=new Date(),end=dateString(today),start=new Date(today);if(range==='semana')start.setDate(start.getDate()-6);if(range==='mes')start.setDate(1);if(range==='ano')start.setMonth(0,1);return {start:range==='personalizado'?customStart:dateString(start),end:range==='personalizado'?customEnd:end,today:end}}
const empty:Summary={metrics:{loans:0,students:0,books:0,active:0},timeline:[],topStudents:[],topBooks:[],grades:[],availableGrades:[]};

export default function DashboardPanel({active}:{active:boolean}){
 const [range,setRange]=useState<Range>('mes'),[customStart,setCustomStart]=useState(''),[customEnd,setCustomEnd]=useState(''),[grade,setGrade]=useState(''),[status,setStatus]=useState('todos'),[data,setData]=useState<Summary>(empty),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const dates=rangeDates(range,customStart,customEnd),valid=!!dates.start&&!!dates.end&&dates.start<=dates.end;
 useEffect(()=>{if(!active||!valid)return;const controller=new AbortController();setLoading(true);setError('');const query=new URLSearchParams({...dates,grade,status});fetch('/api/dashboard?'+query,{signal:controller.signal,cache:'no-store'}).then(async r=>{const result=await r.json() as Summary&{error?:string};if(!r.ok)throw Error(result.error||'Falha ao carregar dados.');setData(result)}).catch(e=>{if(!controller.signal.aborted)setError((e as Error).message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[active,range,customStart,customEnd,grade,status,valid]);
 return <div className="dashboard-page"><div className="page-heading"><div><span className="eyebrow">BIBLIOTECA · ANÁLISE</span><h1>Dashboard</h1><p>Movimentação real dos empréstimos desta escola.</p></div></div>
 <section className="dash-filters" aria-label="Filtros do Dashboard"><div className="dash-range">{([['hoje','Hoje'],['semana','Últimos 7 dias'],['mes','Este mês'],['ano','Este ano'],['personalizado','Período personalizado']] as const).map(([key,label])=><button key={key} type="button" aria-pressed={range===key} className={range===key?'selected':''} onClick={()=>{if(key==='personalizado'&&range!==key){const current=rangeDates(range,'','');setCustomStart(current.start);setCustomEnd(current.end)}setRange(key)}}>{label}</button>)}</div>{range==='personalizado'&&<div className="dash-dates"><label>Data inicial<input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/></label><label>Data final<input type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)}/></label></div>}<div className="dash-selects"><label>Série<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="">Todas as séries</option>{data.availableGrades.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos os empréstimos</option><option value="ativos">Ativos</option><option value="devolvidos">Devolvidos</option><option value="atrasados">Em atraso</option></select></label></div></section>
 {!valid&&<p role="alert" className="dash-error">Informe um período válido.</p>}{error&&<p role="alert" className="dash-error">{error}</p>}{loading&&<p role="status" className="dash-loading">Atualizando dados…</p>}
 <section className="dash-metrics" aria-label="Indicadores">{([['Empréstimos no período',data.metrics.loans],['Alunos atendidos',data.metrics.students],['Livros diferentes emprestados',data.metrics.books],['Empréstimos ativos',data.metrics.active]] as const).map(([label,value])=><div key={label}><span>{label}</span><strong>{value.toLocaleString('pt-BR')}</strong></div>)}</section>
 <section className="dash-section"><div className="dash-heading"><h2>Empréstimos por período</h2><span>Data de entrega</span></div>{data.metrics.loans?<div className="dash-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.timeline} margin={{top:12,right:18,left:-16,bottom:0}}><CartesianGrid stroke="#e9eef3" vertical={false}/><XAxis dataKey="label" tick={{fill:'#607387',fontSize:11}} minTickGap={22} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:'#607387',fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>[value,'Empréstimos']}/><Line dataKey="total" type="monotone" stroke="#17618d" strokeWidth={2.5} dot={data.timeline.length<20} activeDot={{r:5}}/></LineChart></ResponsiveContainer></div>:<p className="dash-empty">Nenhum empréstimo encontrado para estes filtros.</p>}</section>
 <div className="dash-columns"><section className="dash-section"><div className="dash-heading"><h2>Alunos com mais empréstimos</h2></div>{data.topStudents.length?<ol className="dash-ranking">{data.topStudents.map((s,i)=><li key={s.id}><span className="dash-position">{i+1}</span><div><strong>{s.name}</strong><small>{s.grade} · {s.id}</small></div><b>{s.total} {s.total===1?'empréstimo':'empréstimos'}</b></li>)}</ol>:<p className="dash-empty">Nenhum aluno no período.</p>}</section><section className="dash-section"><div className="dash-heading"><h2>Livros mais emprestados</h2></div>{data.topBooks.length?<ol className="dash-ranking">{data.topBooks.map((book,i)=><li key={book.title+'|'+book.author}><span className="dash-position">{i+1}</span><div><strong>{book.title}</strong><small>{book.author}</small></div><b>{book.total}</b></li>)}</ol>:<p className="dash-empty">Nenhum livro no período.</p>}</section></div>
 <section className="dash-section"><div className="dash-heading"><h2>Empréstimos por série</h2></div>{data.grades.length?<div className="dash-grade-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={data.grades} margin={{top:8,right:24,left:12,bottom:8}}><CartesianGrid stroke="#e9eef3" horizontal={false}/><XAxis type="number" allowDecimals={false} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="grade" width={110} tick={{fontSize:12,fill:'#334b5f'}} axisLine={false} tickLine={false}/><Tooltip formatter={(value)=>[value,'Empréstimos']}/><Bar dataKey="total" fill="#24749d" radius={[0,3,3,0]} maxBarSize={28}/></BarChart></ResponsiveContainer></div>:<p className="dash-empty">Nenhuma série no período.</p>}</section></div>
}
