'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {RefreshCw,Activity,Database,Clock} from 'lucide-react';
type Snapshot={status:string;checkedAt:string;databaseMs:number;serverMs:number;version:string;books:{total:number;copies:number;shelves:number};loans:{total:number;active:number;returned:number};users:{total:number};sessions:{total:number}};
type Sample={at:string;ms:number;ok:boolean};
export default function DeveloperPanel({view}:{view:'health'|'stats'}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[samples,setSamples]=useState<Sample[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const running=useRef(false);
 const refresh=useCallback(async()=>{if(running.current)return;running.current=true;setBusy(true);setError('');const start=performance.now();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);try{const res=await fetch('/api/diagnostics',{cache:'no-store',signal:controller.signal});const data=await res.json() as Snapshot&{error?:string};if(res.status===401){window.location.assign('/');return}if(!res.ok)throw Error(data.error||'Falha na verificação.');setSnapshot(data);setSamples(v=>[{at:new Date().toLocaleTimeString('pt-BR'),ms:Math.round(performance.now()-start),ok:true},...v].slice(0,10))}catch(e){setError(e instanceof Error&&e.name==='AbortError'?'O servidor não respondeu em 15 segundos.':(e as Error).message);setSamples(v=>[{at:new Date().toLocaleTimeString('pt-BR'),ms:Math.round(performance.now()-start),ok:false},...v].slice(0,10))}finally{clearTimeout(timeout);running.current=false;setBusy(false)}},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[refresh]);
 const latest=samples[0];
 return <><div className="page-heading"><div><h1>{view==='health'?'Diagnóstico do sistema':'Estatísticas'}</h1><p>Perfil de desenvolvedor · Atualização a cada 30 segundos</p></div><Button variant="outline" onClick={refresh} disabled={busy}><RefreshCw size={16}/>{busy?'Verificando…':'Atualizar'}</Button></div>{error&&<p className="error" role="alert">{error} Os dados abaixo, se exibidos, são da última verificação concluída.</p>}{!snapshot&&!error?<p className="loading">Consultando o sistema…</p>:view==='health'?<><section className="stats diagnostic-stats"><article className="stat"><div>API <Activity size={19}/></div><strong className="health-status">{error?'Falha na consulta':snapshot?'Respondendo':'—'}</strong><small>Estado da última verificação</small></article><article className="stat"><div>Tempo de resposta <Clock size={19}/></div><strong>{latest?.ok?latest.ms:'—'} <span>ms</span></strong><small>Navegador → servidor → navegador</small></article><article className="stat"><div>Consulta ao banco <Database size={19}/></div><strong>{!error&&snapshot?snapshot.databaseMs:'—'} <span>ms</span></strong><small>Teste de leitura no banco</small></article><article className="stat"><div>Processamento da API</div><strong>{!error&&snapshot?snapshot.serverMs:'—'} <span>ms</span></strong><small>Autenticação e consultas desta verificação</small></article></section><section className="panel"><div className="panel-heading"><div><h2>Verificações recentes</h2><p>Últimas 10 medições nesta abertura da aba; não representa disponibilidade histórica.</p></div></div><div className="table-wrap"><table><thead><tr><th>Horário</th><th>Resposta</th><th>Resultado</th></tr></thead><tbody>{samples.map((sample,i)=><tr key={i}><td>{sample.at}</td><td>{sample.ms} ms</td><td>{sample.ok?'Respondendo':'Falha'}</td></tr>)}</tbody></table></div></section></>:snapshot&&<><section className="stats">{[['Livros registrados',snapshot.books.total],['Exemplares',snapshot.books.copies],['Empréstimos registrados',snapshot.loans.total],['Sessões válidas',snapshot.sessions.total]].map(([label,value])=><article className="stat" key={label}><div>{label}</div><strong>{Number(value).toLocaleString('pt-BR')}</strong></article>)}</section><section className="panel"><div className="panel-heading"><h2>Acervo e utilização</h2></div><table><tbody><tr><td>Empréstimos ativos</td><td>{snapshot.loans.active}</td></tr><tr><td>Empréstimos devolvidos</td><td>{snapshot.loans.returned}</td></tr><tr><td>Prateleiras com livros</td><td>{snapshot.books.shelves} de 60</td></tr><tr><td>Perfis cadastrados</td><td>{snapshot.users.total}</td></tr><tr><td>Versão do sistema</td><td>{snapshot.version}</td></tr></tbody></table></section><p className="diagnostic-note">Sessões válidas são acessos ainda não encerrados ou expirados; não indicam pessoas online neste momento.</p></>}{snapshot&&<p className="diagnostic-note">Última consulta concluída: {new Date(snapshot.checkedAt).toLocaleString('pt-BR')}</p>}</>
}
