"use client";
import {useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {filterLabels,labelSizes,type LabelBook,type LabelSize,type LabelsResponse} from './label-rules';
import BookLabel from './book-label';
import {openLabelPrint} from './label-print';
import './labels.css';
export default function LabelsPanel({active,initialId,readonly=false}:{active:boolean;initialId:string|null;readonly?:boolean}){
 const [books,setBooks]=useState<LabelBook[]>([]),[school,setSchool]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[size,setSize]=useState<LabelSize>('50x30'),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(1);
 useEffect(()=>{if(!active)return;const abort=new AbortController();let revision=0;
  async function load(reset:boolean){const request=++revision;if(reset){setLoading(true);setError('')}try{const r=await fetch('/api/labels',{signal:abort.signal}),d=await r.json() as LabelsResponse;if(!r.ok)throw Error(d.error);if(abort.signal.aborted||request!==revision)return;setBooks(d.books);setSchool(d.school);setError('');if(reset){setSelected(initialId?d.books.filter(b=>b.bookId===initialId).map(b=>b.id):[]);setQuery('');setFilter('all');setPage(1);setPreview(Boolean(initialId&&d.books.some(b=>b.bookId===initialId)))}else setSelected(ids=>ids.filter(id=>d.books.some(b=>b.id===id)))}catch(e){if(!abort.signal.aborted&&request===revision)setError((e as Error).message)}finally{if(!abort.signal.aborted&&request===revision)setLoading(false)}}
  const refresh=()=>{load(false)};load(true);window.addEventListener('focus',refresh);return()=>{abort.abort();window.removeEventListener('focus',refresh)}
 },[active,initialId]);
 const filtered=useMemo(()=>filterLabels(books,query,filter),[books,query,filter]);
 const chosen=books.filter(b=>selected.includes(b.id));const pageCount=Math.max(1,Math.ceil(filtered.length/50));const visible=filtered.slice((page-1)*50,page*50);
 useEffect(()=>{setPage(p=>Math.min(p,pageCount))},[pageCount]);
 const toggle=(id:string)=>setSelected(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]);
 const print=(ids=chosen.map(b=>b.id))=>{if(!openLabelPrint(ids,size))setError('Não foi possível abrir a impressão. Permita pop-ups para o SGB e tente novamente.')};
 return <><div className="page-heading"><div><span className="eyebrow">ACERVO</span><h1>Etiquetas e códigos</h1><p>Identificação permanente e impressão dos exemplares.</p></div></div><section className="panel labels-panel">
 <div className="labels-toolbar"><label>Pesquisar<Input aria-label="Pesquisar etiquetas" placeholder="Título, registro, autor ou código" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><label>Etiquetas<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">Todos</option><option value="unprinted">Sem etiqueta</option><option value="printed">Já impressos</option></select></label><label>Tamanho<select value={size} onChange={e=>setSize(e.target.value as LabelSize)}>{Object.entries(labelSizes).map(([key,v])=><option key={key} value={key}>{v.width} × {v.height} mm</option>)}</select></label></div>
 <div className="labels-actions"><span>{selected.length} selecionado(s) · {filtered.length} resultados</span><Button variant="outline" disabled={loading||!filtered.length} onClick={()=>setSelected([...new Set([...selected,...filtered.map(b=>b.id)])])}>Selecionar todos os resultados</Button><Button variant="outline" disabled={!selected.length} onClick={()=>setSelected([])}>Limpar seleção</Button><Button variant="outline" disabled={!chosen.length} onClick={()=>setPreview(true)}>Visualizar etiqueta</Button>{!readonly&&<Button className="primary" disabled={!chosen.length} onClick={()=>print()}>Imprimir selecionados</Button>}</div>
 {error&&<p className="error" role="alert">{error}</p>}{loading?<p className="loading">Carregando exemplares…</p>:<><div className="table-wrap"><table><thead><tr><th>Selecionar</th><th>Registro</th><th>Título / Autor</th><th>Código do exemplar</th><th>Impressões</th><th>Ações</th></tr></thead><tbody>{visible.map(b=><tr key={b.id}><td><input type="checkbox" aria-label={'Selecionar '+b.title+' '+b.code} checked={selected.includes(b.id)} onChange={()=>toggle(b.id)}/></td><td>{b.registration}</td><td><strong>{b.title}</strong><small>{b.authors} · Exemplar {b.copyNumber}</small></td><td className="labels-code">{b.code}</td><td>{b.printCount?`${b.printCount} impressão(ões)`:'Sem etiqueta'}<small>{b.lastPrintedAt?new Date(b.lastPrintedAt.replace(' ','T')+'Z').toLocaleString('pt-BR'):''}</small></td><td>{!readonly&&<button type="button" className="text-action" onClick={()=>print([b.id])}>{b.printCount?'Reimprimir etiqueta':'Imprimir etiqueta'}</button>}</td></tr>)}{!visible.length&&<tr><td colSpan={6}>Nenhum exemplar encontrado.</td></tr>}</tbody></table></div>{pageCount>1&&<nav className="book-pagination" aria-label="Páginas das etiquetas"><button type="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>Página {page} de {pageCount}</span><button type="button" disabled={page>=pageCount} onClick={()=>setPage(p=>p+1)}>Próxima</button></nav>}</>}
 </section><Dialog open={preview} onOpenChange={setPreview}><DialogContent className="labels-preview-dialog"><DialogHeader><DialogTitle>Visualizar etiquetas</DialogTitle><DialogDescription>{chosen.length} etiqueta(s) · {labelSizes[size].width} × {labelSizes[size].height} mm</DialogDescription></DialogHeader><div className="labels-preview-list">{chosen.map(b=><BookLabel key={b.id} book={b} school={school} size={size}/>)}</div>{!readonly&&<Button className="primary" disabled={!chosen.length} onClick={()=>print()}>Imprimir selecionados</Button>}</DialogContent></Dialog></>
}
