"use client";
import {useState,useEffect,useRef,FormEvent} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const USERS_KEY='sgb.remembered-usernames.v1';
function readUsers():string[]{try{const value=JSON.parse(localStorage.getItem(USERS_KEY)||'[]');return Array.isArray(value)?[...new Set(value.filter((item:unknown):item is string=>typeof item==='string'&&/^[a-z0-9._-]{3,50}$/.test(item)))].slice(0,20):[]}catch{return []}}
export default function Login(){
 const[developer,setDeveloper]=useState(false),[devAvailable,setDevAvailable]=useState(false),[setup,setSetup]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[remembered,setRemembered]=useState<string[]>([]),[username,setUsername]=useState(''),[manual,setManual]=useState(true),[password,setPassword]=useState(''),[storageNote,setStorageNote]=useState('');const passwordInput=useRef<HTMLInputElement>(null);
 const creating=setup||developer;
 async function load(){try{const r=await fetch('/api/auth');const d=await r.json() as {setup:boolean;developerSetup:boolean;error:string};if(!r.ok)throw Error(d.error);setSetup(d.setup);setDevAvailable(d.developerSetup);setReady(true)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const users=readUsers();setRemembered(users);if(users.length){setUsername(users[0]);setManual(false)}load()},[]);
 function updateRemembered(users:string[]){setRemembered(users);try{localStorage.setItem(USERS_KEY,JSON.stringify(users))}catch{setStorageNote('Este navegador não permite lembrar usuários. Você pode entrar normalmente.')}}
 function chooseUser(value:string){setUsername(value);setPassword('');setError('');setTimeout(()=>passwordInput.current?.focus(),0)}
 function forgetUser(){const users=remembered.filter(u=>u!==username);updateRemembered(users);setUsername(users[0]||'');setManual(!users.length);setPassword('');setError('')}
 function toggleDeveloper(){setDeveloper(!developer);setUsername('');setManual(true);setPassword('');setError('')}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const data=Object.fromEntries(new FormData(e.currentTarget));data.username=username.trim().toLowerCase();if(creating&&data.password!==data.confirm)throw Error('As senhas não coincidem.');const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,action:developer?'developer-setup':setup?'setup':'login'})});const d=await r.json() as {error:string};if(!r.ok)throw Error(d.error);const users=[data.username,...readUsers().filter(u=>u!==data.username)].slice(0,20);updateRemembered(users);window.location.assign('/sistema')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <main className="login"><div className="login-shade"/><section className="access-card"><div className="logo-window"><img src="/sgb-logo.png" alt="SGB — Sistema de Gestão Bibliotecária"/></div><h1>Biblioteca Lucimar Gomes</h1><p>{developer?'Criar perfil de desenvolvedor':setup?'Configuração inicial da bibliotecária':'Acesso ao sistema'}</p>
 <form onSubmit={submit}>{creating&&<label>Código de ativação<Input name="code" autoComplete="off" required/><small>Informe o código fornecido com o sistema.</small></label>}
 {!creating&&!manual&&remembered.length>0?<div className="remembered-users"><label htmlFor="remembered-user">Usuário neste navegador</label><Select value={username} onValueChange={chooseUser} disabled={busy}><SelectTrigger id="remembered-user" className="remembered-select"><SelectValue placeholder="Selecione o usuário"/></SelectTrigger><SelectContent>{remembered.map(user=><SelectItem key={user} value={user}>{user}</SelectItem>)}</SelectContent></Select><div className="remembered-actions"><button type="button" disabled={busy} onClick={()=>{setManual(true);setUsername('');setPassword('');setError('')}}>Entrar com outro usuário</button><button type="button" disabled={busy} onClick={forgetUser}>Remover da lista</button></div></div>:<label>Usuário<Input name="username" autoComplete="username" pattern="[a-zA-Z0-9._-]{3,50}" value={username} onChange={e=>setUsername(e.target.value)} disabled={busy} required/>{!creating&&remembered.length>0&&<button type="button" className="back-to-users" disabled={busy} onClick={()=>{setManual(false);chooseUser(remembered[0])}}>Selecionar usuário salvo</button>}</label>}
 <label>Senha<Input ref={passwordInput} name="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={creating?'new-password':'current-password'} minLength={10} maxLength={128} disabled={busy} required/></label>
 {creating&&<label>Confirmar senha<Input name="confirm" type="password" autoComplete="new-password" minLength={10} disabled={busy} required/><small>Use pelo menos 10 caracteres.</small></label>}
 {!creating&&<p className="remembered-note">O sistema lembra apenas o usuário neste navegador. A senha será solicitada em cada acesso.</p>}{storageNote&&<p className="remembered-note" role="status">{storageNote}</p>}
 {error&&<div role="alert" className="error">{error}{!ready&&<button type="button" onClick={load}>Tentar novamente</button>}</div>}<Button className="primary" type="submit" disabled={!ready||busy}>{busy?'Aguarde…':!ready?'Carregando…':developer?'Criar desenvolvedor e entrar':setup?'Criar bibliotecária e entrar':'Entrar'}</Button></form>
 {devAvailable&&<button className="developer-activate" disabled={busy} onClick={toggleDeveloper}>{developer?'Voltar ao login':'Ativar perfil de desenvolvedor'}</button>}<footer>SGB <span>Versão 1.0.0</span></footer></section></main>
}
