import {sqliteTable,text,integer,uniqueIndex,index} from "drizzle-orm/sqlite-core";
import {sql} from 'drizzle-orm';
export const books=sqliteTable("books",{id:text("id").primaryKey(),owner:text("owner").notNull(),registration:text("registration").notNull(),data:text("data").notNull()},t=>[uniqueIndex("books_owner_registration").on(t.owner,t.registration)]);
export const loans=sqliteTable("loans",{id:text("id").primaryKey(),owner:text("owner").notNull(),data:text("data").notNull(),studentId:integer('student_id')},t=>[index('loans_owner').on(t.owner),index('loans_owner_student').on(t.owner,t.studentId)]);
export const students=sqliteTable('students',{id:integer('id').primaryKey({autoIncrement:true}),owner:text('owner').notNull(),name:text('name').notNull(),grade:text('grade').notNull(),nameKey:text('name_key').notNull(),gradeKey:text('grade_key').notNull(),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex('students_owner_identity').on(t.owner,t.nameKey,t.gradeKey),index('students_owner_name').on(t.owner,t.nameKey)]);
export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),owner:text('owner').notNull(),salt:text('salt').notNull(),hash:text('hash').notNull(),role:text('role').notNull().default('bibliotecario'),active:integer('active').notNull().default(1),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),lastLoginAt:text('last_login_at').notNull().default(''),displayName:text('display_name').notNull().default('')},t=>[index('users_owner').on(t.owner)]);
export const sessions=sqliteTable('sessions',{token_hash:text('token_hash').primaryKey(),user_id:text('user_id').notNull(),expires:text('expires').notNull(),supportInstitution:text('support_institution')});
export const attempts=sqliteTable('attempts',{key:text('key').primaryKey(),count:text('count').notNull(),until:text('until').notNull()});
export const institutions=sqliteTable('institutions',{
 id:text('id').primaryKey(),code:text('code').notNull().unique(),name:text('name').notNull(),libraryName:text('library_name').notNull().default(''),gre:integer('gre'),cnpj:text('cnpj').notNull().default(''),city:text('city').notNull().default(''),state:text('state').notNull().default(''),cep:text('cep').notNull().default(''),address:text('address').notNull().default(''),addressNumber:text('address_number').notNull().default(''),district:text('district').notNull().default(''),phone:text('phone').notNull().default(''),email:text('email').notNull().default(''),contactName:text('contact_name').notNull().default(''),contactRole:text('contact_role').notNull().default(''),contactPhone:text('contact_phone').notNull().default(''),contactEmail:text('contact_email').notNull().default(''),logoUrl:text('logo_url').notNull().default(''),activatedAt:text('activated_at').notNull().default(''),status:text('status').notNull().default('ativa'),notes:text('notes').notNull().default(''),licensePlan:text('license_plan').notNull().default('Educacional'),licenseStatus:text('license_status').notNull().default('Ativa'),licenseStart:text('license_start').notNull().default(''),licenseEnd:text('license_end').notNull().default(''),licenseNotes:text('license_notes').notNull().default(''),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`)
});
export const auditLogs=sqliteTable('audit_logs',{id:text('id').primaryKey(),institutionId:text('institution_id').notNull(),userId:text('user_id').notNull(),action:text('action').notNull(),details:text('details').notNull().default(''),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index('audit_logs_institution_created').on(t.institutionId,t.createdAt)]);
// Identidades permanentes, independentes do registro e do ISBN.
export const bookLabels=sqliteTable('book_labels',{
 id:integer('id').primaryKey({autoIncrement:true}),bookId:text('book_id').notNull(),copyNumber:integer('copy_number').notNull(),owner:text('owner').notNull(),institutionCode:text('institution_code').notNull(),
 code:text('code').generatedAlwaysAs(sql`'SGB-' || institution_code || '-' || printf('%06d', id)`).notNull(),
 printCount:integer('print_count').notNull().default(0),lastPrintedAt:text('last_printed_at'),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)
},t=>[uniqueIndex('book_labels_book_copy').on(t.bookId,t.copyNumber),uniqueIndex('book_labels_code').on(t.code),index('book_labels_owner').on(t.owner)]);
export const labelPrintEvents=sqliteTable('label_print_events',{
 jobId:text('job_id').notNull(),labelId:integer('label_id').notNull().references(()=>bookLabels.id),printedAt:text('printed_at').notNull().default(sql`CURRENT_TIMESTAMP`)
},t=>[uniqueIndex('label_print_events_job_label').on(t.jobId,t.labelId)]);
