import {sqliteTable,text,integer,uniqueIndex,index} from "drizzle-orm/sqlite-core";
import {sql} from 'drizzle-orm';
export const books=sqliteTable("books",{id:text("id").primaryKey(),owner:text("owner").notNull(),registration:text("registration").notNull(),data:text("data").notNull()},t=>[uniqueIndex("books_owner_registration").on(t.owner,t.registration)]);
export const loans=sqliteTable("loans",{id:text("id").primaryKey(),owner:text("owner").notNull(),data:text("data").notNull()},t=>[index('loans_owner').on(t.owner)]);
export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),owner:text('owner').notNull(),salt:text('salt').notNull(),hash:text('hash').notNull(),role:text('role').notNull().default('bibliotecario'),active:integer('active').notNull().default(1),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),lastLoginAt:text('last_login_at').notNull().default(''),displayName:text('display_name').notNull().default('')},t=>[index('users_owner').on(t.owner)]);
export const sessions=sqliteTable('sessions',{token_hash:text('token_hash').primaryKey(),user_id:text('user_id').notNull(),expires:text('expires').notNull(),supportInstitution:text('support_institution')});
export const attempts=sqliteTable('attempts',{key:text('key').primaryKey(),count:text('count').notNull(),until:text('until').notNull()});
export const institutions=sqliteTable('institutions',{
 id:text('id').primaryKey(),code:text('code').notNull().unique(),name:text('name').notNull(),libraryName:text('library_name').notNull().default(''),cnpj:text('cnpj').notNull().default(''),city:text('city').notNull().default(''),state:text('state').notNull().default(''),cep:text('cep').notNull().default(''),address:text('address').notNull().default(''),addressNumber:text('address_number').notNull().default(''),district:text('district').notNull().default(''),phone:text('phone').notNull().default(''),email:text('email').notNull().default(''),contactName:text('contact_name').notNull().default(''),contactRole:text('contact_role').notNull().default(''),contactPhone:text('contact_phone').notNull().default(''),contactEmail:text('contact_email').notNull().default(''),logoUrl:text('logo_url').notNull().default(''),activatedAt:text('activated_at').notNull().default(''),status:text('status').notNull().default('ativa'),notes:text('notes').notNull().default(''),licensePlan:text('license_plan').notNull().default('Educacional'),licenseStatus:text('license_status').notNull().default('Ativa'),licenseStart:text('license_start').notNull().default(''),licenseEnd:text('license_end').notNull().default(''),licenseNotes:text('license_notes').notNull().default(''),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`)
});
export const auditLogs=sqliteTable('audit_logs',{id:text('id').primaryKey(),institutionId:text('institution_id').notNull(),userId:text('user_id').notNull(),action:text('action').notNull(),details:text('details').notNull().default(''),createdAt:text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index('audit_logs_institution_created').on(t.institutionId,t.createdAt)]);
